// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC921TAPdGdMzcXtjDgjVpirmBjUXFNgb0',
    appId: '1:845972064283:web:27f7553da96062733790be',
    messagingSenderId: '845972064283',
    projectId: 'servicedesk-704ec',
    authDomain: 'servicedesk-704ec.firebaseapp.com',
    storageBucket: 'servicedesk-704ec.firebasestorage.app',
    measurementId: 'G-VMSGV03WRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH1FbpqlNL9B8iAWz6HjVx_o2TKbQ9UPk',
    appId: '1:845972064283:android:435e94bba21ee5d43790be',
    messagingSenderId: '845972064283',
    projectId: 'servicedesk-704ec',
    storageBucket: 'servicedesk-704ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVNQrT2r-jqcT4828W-mJ-MYKJo8kYuM',
    appId: '1:845972064283:ios:3945c68a33c6edd33790be',
    messagingSenderId: '845972064283',
    projectId: 'servicedesk-704ec',
    storageBucket: 'servicedesk-704ec.firebasestorage.app',
    iosClientId: '845972064283-14d2ftakkau47e513bbu6fpesa4mk2g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicedesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGVNQrT2r-jqcT4828W-mJ-MYKJo8kYuM',
    appId: '1:845972064283:ios:3945c68a33c6edd33790be',
    messagingSenderId: '845972064283',
    projectId: 'servicedesk-704ec',
    storageBucket: 'servicedesk-704ec.firebasestorage.app',
    iosClientId: '845972064283-14d2ftakkau47e513bbu6fpesa4mk2g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicedesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC921TAPdGdMzcXtjDgjVpirmBjUXFNgb0',
    appId: '1:845972064283:web:89b419b541268e663790be',
    messagingSenderId: '845972064283',
    projectId: 'servicedesk-704ec',
    authDomain: 'servicedesk-704ec.firebaseapp.com',
    storageBucket: 'servicedesk-704ec.firebasestorage.app',
    measurementId: 'G-0J9SCPPH6M',
  );
}
